# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: sam-app-two

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# adds layer to all functions in this app
Globals:
  Function:
    Timeout: 3
    Layers:
      - !Ref AppLayer

Parameters:
  Environment:
    Type: String
    Default: dev

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-day-of-week.js
  getDayOfWeekFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/GetDayOfWeek
      Handler: index.getDayOfWeekHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to return the current day of the week.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /day
            Method: GET

  getNamedColorRgbValuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/GetNamedColorRgbValues
      Handler: index.getNamedColorRgbValuesHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: HTTP get method to return the RGB values for a named color.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /colors/{name}
            Method: GET

  AppLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: App specific dependencies
      ContentUri: layer/nodejs
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs14.x

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
